<?php 
if (!$this->flag) {
?>
<script type="text/javascript">
<!--

$(function() {
	$("#progresbar").progressbar({
		value: <?php echo $this->value;?>});
});
ev.time=2000;
function refreshbar() {
	ev.request('admin/index/loader','post',{flag:1},function(data){
		if (data.data>0) {
			$("#progresbar").progressbar("value",data.data);
			perc=$("#progresbar div").text();
			perc=perc.substr(0,perc.length-1);
		//alert(perc+'time '+ev.time+' data '+data.data);
			if (perc>=data.data) ev.time*=2;
			else {if ((perc<data.data)&&(ev.time>2000)) ev.time/=2;}
			$("#progresbar div").text(data.data+"%");
			}
			if (data.data<100) setTimeout(refreshbar,ev.time);
			else $("#image").attr("src","<?php echo $this->baseUrl();?>/admin/generate/image");
		
	});
}

setTimeout(refreshbar,ev.time);

//-->
</script>
<div id="progresbar">
</div>

<button onclick="ev.request('admin/generate/map','post');refreshbar()">esegui</button>
<button onclick="refreshbar();">refresh</button>

<div><img id="image" src="" alt="loading..."></div>
<?php 
}
else {
echo json_encode(array('data'=>array($this->value,$this->comment),'html'=>false,'update'=>false,'javascript'=>false));
}
?>