<?php
$this->headTitle("s1");
$this->headTitle("index");
$t = Zend_Registry::get("translate");
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
if ($this->hasCivilty > 1) {
    //lascia spazio alla mappa 24x18
    
    //$cache=$this->village['cache'];
    /*foreach ($this->village['cache'] as $x => $value) {
    	foreach ($value as $y => $v) {
    		$cache[$x][$y]=$v;
    	}
    }*/
    $x=$this->x;
    $y=$this->y;
    $this->headScript()->captureStart();
    
    echo 'function keyDown(event) {
    if (event.which == null)
        key= (event.keyCode);    // IE
    else key=event.which;
    x=ev.map.centre[0];
    y=ev.map.centre[1];
    bool=true;
    switch (key) {
        case 37:x--;
        break;
        case 38:y++;
        break;
        case 39:x++;
        break;
        case 40:y--;
        break;
        default:bool=false;
    }
    if (bool) {ev.map.position(x,y);return false;}
	}
$(document).keydown(keyDown);
	ev.map.centre=['.intval($x).','.intval($y).'];
	ev.map.init=['.intval($x).','.intval($y).'];
    
    ev.map.size=['.intval($this->zoom['x']).','.intval($this->zoom['y']).','.$this->zoom['dim'].'];
    
    var menu=[{"'.$t->_('rinforza').'":{onclick:ev.support,icon:"'.$this->baseUrl('/common/images/inrinfo.png').'"}},
		{"'.$t->_('raid').'":{onclick:ev.raid,icon:"'.$this->baseUrl('/common/images/outattack.png').'"}},
		{"'.$t->_('attacca').'":{onclick:ev.atk,icon:"'.$this->baseUrl('/common/images/inattack.png').'"}},
		{"'.$t->_('colonizza').'":{onclick:ev.colony,icon:"'.$this->baseUrl('/common/images/pop.gif').'"}},
		{"'.$t->_('invia mercanti (non implementato)').'":{onclick:ev.market,icon:"'.$this->baseUrl('/common/images/market.png').'"}}	
	];
	$(function () {
		$(".map_village").contextMenu(menu,{theme:"human"});
		if (m=location.hash.match(/(\d+)\|(\d+)(@*)/)) {
        // #2|2-dsf
        console.log(m);
        	x=parseInt(m[1]);
        	y=parseInt(m[2]);
        	console.log(x,y);
            ev.map.position(x,y,m[3]? ev.map.get_village_info:null);
        	
		}else ev.map.position('.$x.','.$y.');
			'.($this->vid ? 'location.hash = "#'.$this->x.'|'.$this->y.'";ev.map.load_detail();':'').'
		
	});';
    $this->headScript()->captureEnd();
    echo '<div id="map_details" style="display: none; position:absolute;z-index:200;">
<table>
	<thead>
		<tr>
			<th colspan="2" id="village_name">'.$t->_("Valle Inabitata").'</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>'.$t->_("Civilt&aacute;").':</td>
			<td id="village_player">-</td>
		</tr>
		<tr>
			<td>'.$t->_("Alleanza").':</td>
			<td id="village_ally">-</td>
		</tr>
		<tr>
			<td>'.$t->_("Popolazione").':</td>
			<td id="village_popol">-</td>
		</tr>
		<tr>
			<td>'.$t->_("Bonus").':</td>
			<td id="village_bonus"></td>
		</tr>
		<tr>
			<td colspan="2"><a href="#" id="send_link">'.$t->_("Invia truppe").'</a></td>
		</tr>
	</tbody>
</table>
</div>';
    echo '<div id="map" style="position:absolute;width: 1200px; height: 900px;top:0;">';
    echo $this->table.'</div>';
    
} elseif ($this->hasCivilty == 1) {
    echo '<h1>' . $t->_('sei in attesa') . '</h1>' .
     $t->_('la civilt&aacute; a cui ti sei iscritto non ti ha ancora attivato');
} else {
    ?>
non hai civilt&agrave;
<p><strong>unisciti ad una civilt&agrave;</strong> <br />
<input type="hidden" value="0" id="start" /> <input id="civ_name" size="20" maxlength="30" />
<button onclick="ev.SearchCiv(0)"><?php
    echo $t->_("Cerca");
    ?></button>
</p>
<div id="result"></div>

<h2>crea una nuova civilt&agrave;</h2>
<span id="load"></span>
<center>
<div id="mess">
	<?php
    echo $this->form;
    ?>
</div>
</center>
<?php
}
?>   