<?php
$x=$this->x;
$y=$this->y;
$module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
$this->headTitle($module);
$this->headTitle("index");
$t = Zend_Registry::get("translate");
 $this->headScript()->captureStart();
    
    echo 'function keyDown(event) {
    if (event.which == null)
        key= (event.keyCode);    // IE
    else key=event.which;
    x=ev.map.centre[0];
    y=ev.map.centre[1];
    bool=true;
    switch (key) {
        case 37:ev.map.centre[0]--;
        break;
        case 38:ev.map.centre[1]++;
        break;
        case 39:ev.map.centre[0]++;
        break;
        case 40:ev.map.centre[1]--;
        break;
        default:bool=false;
    }
    if (bool) {ev.map.shift();return false;}
	}
	$(document).keydown(keyDown);
	ev.map.centre=['.intval($x).','.intval($y).'];
    ev.map.size=['.intval($this->zoom['x']).','.intval($this->zoom['y']).','.$this->zoom['dim'].'];
    $(function(){
    	ev.map.init();
    	$("#modalwindows").dialog({modal:true});
    	$("#map").draggable({
    		grid: [50,50],
    		revert: true,
    		cursor:"move",
    		helper:function(){
    			return $(\'<div></div>\');
    		},
    		start: function(e,ui) {
    			ev.map.pos=ui.position;
    			ev.map.prev={top:0,left:0};
    			ev.ondrag=true;
    		},
    		stop: function() {
    			ev.ondrag=false;
    		},
    		drag:function(e,ui){
    			t=Math.round((ev.map.pos.top-ui.position.top)/50);
    			l=-Math.round((ev.map.pos.left-ui.position.left)/50);
    			//console.log(l,t);
    			bool=false;
    			if (ev.map.prev.top!=t) {
    				ev.map.centre[1]-=t-ev.map.prev.top;
    				ev.map.prev.top=t;
    				bool=true;
    			}
    			if (ev.map.prev.left!=l) {
    				ev.map.centre[0]-=l-ev.map.prev.left;
    				ev.map.prev.left=l;
    				bool=true;
    			}
    			if (bool) ev.map.shift();
    		},
    		//cursorAt: { top: 25, left: 25 },
    	})
    });
    ';
$this->headScript()->captureEnd();
?>
<div id="map_details" style="display: none; position:absolute;z-index:200;">
<table>
	<thead>
		<tr>
			<th colspan="2" id="village_name">[Valle Inabitat]</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>[Civilt&aacute;]:</td>
			<td id="village_player">-</td>
		</tr>
		<tr>
			<td>[Alleanza]:</td>
			<td id="village_ally">-</td>
		</tr>
		<tr>
			<td>[Popolazione]:</td>
			<td id="village_popol">-</td>
		</tr>
		<tr>
			<td>[Bonus]:</td>
			<td id="village_bonus"></td>
		</tr>
		<!-- add more options -->
	
		<!-- <tr>
			<td colspan="2"><a href="#" id="send_link">[Invia truppe]</a></td>
		</tr> -->
	</tbody>
</table>
</div>
<div id="map" style="position:absolute;width: 1200px; height: 900px;top:0;"><?php         
        $gap=0;$n=0;
        for($j=1;$j<=$this->zoom['y'];$j++) {
            for ($i=1;$i<=$this->zoom['x'];$i++) {
            	echo '<div style="position:relative;left:'.(($i-1)*$this->zoom['dim']).'px;top:'.($gap+($j-1)*$this->zoom['dim']).'px;" 
            				class="map zoom-'.$this->zoom['dim'].'" id="map_village_' . $i .
                 '_'.$j.'" onmouseover="ev.map.details('.($i-1).','.($j-1).','.$n++.');" 
            				onmouseout="ev.map.hide_map_details();" 
            				onclick="if (!ev.drag) ev.map.get_village_info('.($i-1).','.($j-1).',false); else ev.drag=false;" alt="'.($n-1).'" ><div class="zoom-'.$this->zoom['dim'].' map-null"><!--vilage--><div class="zoom-'.$this->zoom['dim'].' map-null"><!--flag--></div></div></div>';
            	$gap-=50;
            }
        }
?></div>
<?php 

if ($this->hasCivilty > 1) {
	
    $this->headScript()->captureStart();
	echo '
    var menu={
    	reinf: {
    		name:"[rinforza]",
    		callback:function(k,opt) {
    			ev.support(opt);
    		},
    		icon:"icon inReinf"
		},
		raid: {
			name:"[raid]",
			callback:function(k,opt) {
				ev.raid(opt)
			},
			icon:"icon outAttack"
		},
		atk: {
			name:"[attacca]",
			callback:function(k,opt) {
				ev.atk(opt)
			},
			icon:"icon inAttack"
		},
		colony: {
			name:"[colonizza]",
			callback:function(k,opt) {
				ev.colony(opt)
			},
			icon:"pop"
		},
		market: {
			name:"[invia mercanti (non implementato)]",
			callback:function(k,opt) {
				ev.market(opt)
			},
			icon:"icon marketM",
			disabled:true
		}	
	};
	$(function () {
    	ev.village.init();
		$.contextMenu({
			selector:".map",
			items:menu
		});
		if (m=location.hash.match(/(-*\d+)\|(-*\d+)(@*)/)) {
        // #2|2-dsf
        console.log(m);
        	x=parseInt(m[1]);
        	y=parseInt(m[2]);
        	console.log(x,y);
        	ev.map.centre=[x,y];
            //ev.map.shift();
        	
		}
			'.($this->vid ? 'location.hash = "#'.$this->x.'|'.$this->y.'";ev.map.load_detail();':'').'
	});';
    $this->headScript()->captureEnd();

    
} elseif ($this->hasCivilty == 1) {
	?><div id="modalwindows" title="[ONWAIT]"  class="notooltip">
		[WAITFORCIV]
		<button onclick="ev.request(module+'/index/unsubscrive','get',null,function(){location.reload();});">[WITHDRAW]</button>
    </div>
     <?php 
} else {
    ?>
<div id="modalwindows" class="notooltip" title="[NOCIV]">
	<h3>[FINDCIV]</h3>
	<input type="hidden" value="0" id="start" /><input id="civ_name" size="20" maxlength="30" />
	<button onclick="ev.SearchCiv(0)">[SEARCH]</button>
	<div id="result"></div>
	
	<h3>[CREATECIV]</h3>
	<span id="load"></span>
	<div id="mess">
	<?php
    	echo $this->form;
    ?>
	</div>
</div>
<?php
}
?>   