<?php
$t=Zend_Registry::get("translate");


/**
 * visualizza il villaggio
 */
global $Building_Array;
// barra risorse
$now = $this->civ->getCurrentVillage();
$this->layout()->id=$now;
$this->headTitle($this->template()->village($now,null,false));
echo '<div id="resbar'.$now.'">' . $this->template()->resourceBar() . '</div>';
// villaggio
if ($this->civ->data['ev_ready']) {
    echo '<a href="' . $this->url(array('controller'=>'ev','action'=>'index')) . '">' . $this->image(
    '/common/images/evolve.gif', $t->_('evolvi'), null, 150, 51) . '</a>';
}
$bonus = $this->civ->village->data[$now]['defence'];
echo '<span style="color:' . ($bonus < 100 ? 'red' : 'green') . ';">' .
 $t->_('Bonus difesa') . ': ' . $bonus . '%</span>';
//pannello costruzioni
echo '<div class="pannel">';
for ($i = 2; $i <= TOT_TYPE_BUILING; $i ++) {
    //$this->disp
    $name = Model_building::$name[$this->civ->getAge()][$i];
    echo '<div style="height: 10px;"></div><div id="' . $i .
     '" class="building drag ' . $Building_Array[$i - 1] .
     '" style="z-index:200;' . ($this->disp[$i] ? "" : "display:none;") .
     '"> <a href="#"><input type="hidden" class="Btype" value="' . $i .
     '"/><img src="' . $this->baseUrl() .
     '/common/images/void.png" width="100" height="100" alt="' . $name .
     '" title="' . $name . ' liv 0" /></a> </div>';
}
echo '</div><div class="village_view">';
$log = Zend_Registry::get("log");
//$log->log($this->civ->village->building[$now]->data, Zend_Log::DEBUG);
for ($i = 0; $i <= TOTBUILDING; $i ++) {
    if ($this->civ->village->building[$now]->data != NULL && isset(
    $this->civ->village->building[$now]->data[$i])) {
        $type = $this->civ->village->building[$now]->data[$i]['type'];
        $name = Model_building::$name[$this->civ->getAge()][$type];
        $liv = $this->civ->village->building[$now]->data[$i]['liv'];
        echo '<div class="building pos' . $i . ' ' . $Building_Array[$type - 1] .
         '"> <a href="' .
         $this->url(
        array( 'controller' => 'building', 
        'action' => 'show', 'pos' => $i)) . '"><img src="' . $this->baseUrl() .
         '/common/images/void.png" width="100" height="100" alt="' . $name .
         '" title="' . $name . ' liv ' . $liv . '" /></a> </div>';
    } else {
        echo '<div class="building pos' . $i . ' empty"> <a href="' .
         $this->url(
        array( 'controller' => 'building', 
        'action' => 'show', 'pos' => $i)) . '"><img src="' . $this->baseUrl() .
         '/common/images/void.png" width="100" height="100" alt="' .
         $t->_("costruisci") . '" title="' . $t->_("costruisci") .
         '" /></a> </div>';
    }
}
echo '</div><br />';
// coda costruzioni
$queue = $this->civ->getQueue();
echo '<h3>' . $this->t->_('costruzioni') . '</h3><div id="queue'.$now.'">' .
 $this->template()->queue($queue);
echo '</div><h3>' . $this->t->_('demolizioni') . '</h3><div id="destroy'.$now.'">';
$destroy = $this->civ->destroy;
echo $this->template()->queue($destroy);
echo '</div>';
//@todo sistemare il drag, rimettere apposto l'oggetto se non ci sono le condizioni per costruire
$this->headScript()->captureStart();
?>
	$("body").ready(function() {
	ev.token.tokenB='<?php
echo token_set("tokenB");
?>';
	$('.building:not(.empty)','.village_view').contextMenu(ev.menubuilding,{theme:'human'});
		$("div.drag").draggable({
				revert : "invalid",
				helper : "clone",
				cursor : "move",
		});
		$("div.empty").droppable({
				accept : ".drag",
				drop : function(event, ui) {
					$item=ui.draggable;
					c=$item.attr("class")
					$item.fadeOut(function() {
						$(event.target).removeClass("empty");
						$(event.target).addClass(c);
						$('img',event.target).attr('title',$('img',$item).attr('title'));
					});
					//$item.appendTo($('#pannel'));
					m=$(event.target).attr("class").match(/pos(\d+)/);
					t=$item.find(".Btype").val();
					ev.request(module+'/building/build/type/'+t+'/pos/'+m[1]+'/tokenB/'+ev.token.tokenB,'post',{ajax:1});
				}
		});
     }); 
     
	<?php
$this->headScript()->captureEnd();
?>