<h3><a href="http://blogpagliaccio.wordpress.com" target="_blanc" >Pagliaccio</a></h3>
<p>
    Ideatore, amministratore e realizzatore del gioco. Programmatore php, javascript.
</p>
<h3><a href="http://leonardosite.altervista.org" target="_blanc" >Leonardo I</a></h3>
<p>
    Co-amministratore e realizzatore del gioco. Programmatore php, javascript.
</p>



<h3>ringraziamo i segunti tool per il supporto dato:</h3>

    <a href="http://validator.w3.org/check?uri=referer">
        <img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0 Transitional" height="31" width="88" />
    </a>

<a href="http://www.linux.org"><img src="<?php echo $this->baseUrl()?>/common/images/linux_icon.gif" alt="linux" height="60" width="65" /></a>
<a href="http://apache.org/"><img src="<?php echo $this->baseUrl()?>/common/images/apache_icon.gif" alt="apache" height="50" width="72" /></a>
<a href="http://www.mysql.it"><img src="<?php echo $this->baseUrl()?>/common/images/mysql_icon.gif" alt="mysql" height="37" width="63" /></a>
<a href="http://www.php.net"><img src="<?php echo $this->baseUrl()?>/common/images/php_icon.gif" alt="php" height="35" width="44" /></a>
<a href="http://www.zend.com/"><img src="<?php echo $this->baseUrl()?>/common/images/zend.png" alt="zend" height="50" width="50" /></a>
