<?php
$t=Zend_Registry::get("translate");
$stato = array("", $t->_("in attesa"), $t->_("sharer"), $t->_("owner"));
$uid=Zend_Auth::getInstance()->getIdentity()->user_id;
$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
echo '
<form method="post" action="'.$this->baseUrl().'/'.$module.'/sharer/perm/tokenSh/' . $this->token . '">
	<table>
		<tr>
			<td></td>
			<td>' . $t->_("nome") . '</td>
			<td>' . $t->_("ruolo") . '</td>';
for ($j = 0; $this->option[$j]; $j ++) {
    echo '	<td><abbr title="' . $this->option[$j]['title'] . '">' . $this->option[$j]['abbr'] .
     '</abbr></td>';
}
echo '	</tr>';
for ($i = 0; $this->sharer[$i]; $i ++) {
    if ($this->sharer[$i]['last_activity'] > strtotime("-15 minutes"))
        $act = 1;
    elseif ($this->sharer[$i]['last_activity'] > strtotime("-1 days"))
        $act = 2;
    elseif ($this->sharer[$i]['last_activity'] > strtotime("-3 days"))
        $act = 3;
    elseif ($this->sharer[$i]['last_activity'] > strtotime("-7 days"))
        $act = 4;
    else
        $act = 5;
    echo '<tr>
                <td>' .
     (($this->sharer[$i]['status'] == 3) ||
     ($this->sharer[$i]['user_id'] == $uid) ? '' : '<a href="'.$this->baseUrl().'/'.$module.'/sharer/delete/uid/' .
     $this->sharer[$i]['user_id'] . '/tokenSh/' . $this->token . '"><img src="' . $this->baseUrl() .
     '/common/images/del.gif" alt="delete" /></a>') .
     '
		    ' .
     ($this->sharer[$i]['status'] == 1 ? '<a href="'.$this->baseUrl().'/'.$module.'/sharer/add/uid/' .
     $this->sharer[$i]['user_id'] . '/tokenSh/' . $this->token . '"><img src="' . $this->baseUrl() .
     '/common/images/ok.gif" alt="ok" /></a>' : '') . '</td>
                <td> ' .
     $this->sharer[$i]['username'] . '</td>
                <td>' .
     $stato[$this->sharer[$i]['status']] . '</td>';
    if ($this->sharer[$i]['status'] != 3) {
        for ($j = 0; $this->option[$j]; $j ++) {
            echo '<td><input type="checkbox" name="' . $this->option[$i]['name'] .
             $this->sharer[$i]['user_id'] . '" value="true" /></td>';
        }
    }
    echo '</tr>';
}
echo '
	</table>
	<input type="submit" value="' . $t->_("salva") . '"/>
</form>'
?>