<?php
$t=Zend_Registry::get("translate");
//$debug=true;
//token
global $NameTroops,$Troops_Array;
echo '<script type="text/javascript">resetinit();</script>
	<table class="troopers" style="margin-left: 10px;">
	<thead><td></td>
	<td>' . $t->_("numero") . '</td>
	<td>' . $t->_("durata") . '</td>
	<td>' . $t->_("finito") . '</td></thead>';
for ($i = 0; $this->training[$i]; $i++) {
    $params = unserialize($this->training[$i]['params']);
    $dif = $this->training[$i]['time'] - mktime();
    if ($dif <= 0)
        $dif = "00:00:0?";
    
    echo '<tr><td>' . $this->image()->Troop($params['trooper_id']) . '</td>
		<td>' . $params['num'] . '</td>
		<td><span class="countDown">' . $dif . '</span> </td>
			<td>' . date("H:i:s", $this->training[$i]['time']) . '</td></tr>';
}
echo "</table><br/>";
if ($this->section == 1) {
    echo '<form action="'.$this->url(array('controller'=>'trainer','action'=>'train','tokenT'=>$this->token)).'" method="post" name="modulo">';
    foreach ($this->disp as $key => $value) {
        echo '<div style="padding-left: 10px;"><span style="border: 1px solid black;padding: 8px 3px 8px 2px;">' . $this->image()->troop($value) . ' &nbsp &nbsp ';
        $res = $Troops_Array[$value]::$cost;
        $tot=0;
        for ($i = 0; $i < 3; $i++) {
        	$tot+=$res[$i];
            echo $res[$i] . ' ' . $this->image()->resource($i, $this->age) . ' &nbsp &nbsp ';
        }
        
        $tadd = intval($tot / $this->p['rid']*3600);
        echo $res[$i] . ' '.$this->image()->resource(3,$this->age).'
			' . timeStampToString($tadd) . ' ';
        //max con le risorse
                $max = $this->p['liv'] * $this->p['maxpop'];
                $temp = $max;
                for ($i = 0; $i < 3; $i ++) {
                    $reso = "resource_" . ($i + 1);
                    if ($res[$i])
                        $temp = intval(
                        $this->res[$reso] / $res[$i]);
                    if ($temp < $max)
                        $max = $temp;
                }
                $popl = $this->popl;
                if ($popl > 0)
                    $temp = intval($popl / $res[3]);
                else
                    $max = 0;
                if ($temp < $max)
                    $max = $temp;
        
        echo'<input name="t' . $value . '" size="3" /><a onclick="document.modulo.t' . $value . '.value=' . $max . ';">(' . $max . ')</a></span></div><br/>';
    }
    echo '<input value="' . $t->_('addestra') . '" type="submit" /></form>';
}
elseif ($this->section=="2") {
	$log=Zend_Registry::get("log");
    $troop = $this->troop;
    echo '<form action="'.$this->url(array('controller'=>'trainer','action'=>'promote','tokenT'=>$this->token)).'" method="post" name="modulo">';
    foreach ($troop as $key => $value) {
        if ($Troops_Array[$key]::$age < $this->age) {
            echo '<div style="padding-left: 10px;">' . $this->image()->troop($key) . '
               -> <select id="type" style="padding-left: 20px;background: #FFF url('.$this->baseUrl().'/common/images/troops/t' . $this->disp[0] . '.gif) no-repeat;" name="type' . $key . '" onchange="ev.changeimg(this)">';
            for ($j = 0; $this->disp[$j]; $j++) {
                echo '<option value="' . $this->disp[$j] . '" style="padding-left: 20px;background: #FFF url('.$this->baseUrl().'common/images/troops/t' . $this->disp[$j] . '.gif) no-repeat;">' . $NameTroops[$this->disp[$j]] . '</option>';
            }
            $cost = $Troops_Array[$this->disp[0]]::$cost[0] +
                 $Troops_Array[$this->disp[0]]::$cost[1] +
                 $Troops_Array[$this->disp[0]]::$cost[2] -
                 $Troops_Array[$key]::$cost[0] -
                 $Troops_Array[$key]::$cost[1] -
                 $Troops_Array[$key]::$cost[2];
                 $pop=$Troops_Array[$key]::$cost[3]-$Troops_Array[$this->disp[0]]::$cost[3];
                 
                //max con le risorse
                $max = $value['numbers'];
                $temp = $max;
                if ($cost)
                    $temp = intval($this->resource_1 / $cost);
                if ($temp < $max)
                    $max = $temp;
                $popl = $this->popl;
                if (($popl > 0) && ($pop != 0))
                    $temp = intval($popl / $pop);
                if ($temp < $max)
                    $max = $temp;
            echo'</select>
                <input name="t' . $key . '" size="3" /><a onclick="$(\'input[name=t' . $key . ']\').val(' . $max . ');">(' . $max . ')</a>
                &nbsp; &nbsp; <span id="cost' . $key . '">' . $cost . '</span> ' . $this->image()->resource(0, $this->age) . '
                </div>';
        }
    }
    echo '<input value="' . $t->_('Promuovi') . '" type="submit" /></form>';
}
echo '</div>';
?>