<div id="dialog" title="[CONFIRM]">
[DELETE_CONFIRM]
<div>Password :<input id="delete" type="password" /></div>
</div>
<form class="profile">
<table style="width: 300px;">
  <tr id="username">
    <td>[USERNAME]</td>
    <td><span>NICK</span><input name="username" style="display:none;" required="required" value="NICK" /></td>
<?php 
if ($this->can) {
?>
    <td><button class="edit profile">[EDIT]</button></td>
<?php 
}
?>
  </tr>
  <tr id="email">
    <td>Email :</td>
    <td><span>EMAIL</span><input name="email" type="email" required="required" style="display:none;" value="EMAIL" /></td>
    <td><button class="edit profile">[EDIT]</button></td>
  </tr>
<?php 
foreach ($this->option as $key => $value) {
	if (!$value['label']) $value['label']=$value['value'];
	echo '<tr id="'.$key.'">
		<td>'.$value['name'].'</td>
		<td><span>'.$value['label'].'</span>';
	if (!$value['type']) $value['type']='Text';
	$value['attr']['style']='display:none;';
	if ($value['required']) $value['attr']['required']='required';
	$helper='form'.$value['type'];
	echo $this->$helper($key,$value['value'],$value['attr'],$value['option']);
	//$h=new Zend_View_Helper_FormSelect();$h->formSelect($name);
	//		<input '.(?'required="required"':'').' name="'.$key.'" style="display:none;" value="'.$value['value'].'" /></td>
	echo'<td><button class="edit profile">[EDIT]</button></td>
	</tr>';
}
?>
  <tr>
    <td class="button" colspan="3"><button>[CHANGEPASS]</button> <button>[DELETE] account</button></td>
  </tr>
  <tr class="passwordpanel">
  	<td>[OLD_PASS] :</td>
  	<td colspan="2"><input name="password" type="password" /></td>
  </tr>
  <tr class="passwordpanel">
  	<td><input id="password" name="new" type="password" /></td>
  	<td colspan="2"><input name="new2" type="password" /></td>
  </tr>
</table>
</form>


<?php /*
$t=Zend_Registry::get("translate");
?>
<form name="account" action="<?php echo $this->baseUrl(); ?>/account/index/tokenP/<?php echo $this->token;?>" method="post">
<?php 
	//echo $this->pass->render();
	echo $this->pass->getElement("password")->render();
	echo $this->pass->getElement("newpass")->render();
	echo $this->pass->getElement("newpass2")->render();
	/*<h3><?php echo $t->_("Cambia password");?></h3>
<div><?php echo $t->_("Vecchia password");?>:<input name="pass"  size="10" type="password" /></div>
<div><?php echo $t->_("Nuova password");?>:<input name="newpass" class="passwordpanel" size="10" type="password" /></div>
<?php echo $t->_("Ripeti");?>:<input name="newpass2" class="passwordpanel" size="10" type="password" />
?>
<h3><?php echo $t->_("Cambia email");?></h3>
<div><input disabled="disabled" name="email" size="10"/></div>
<?php
$sel = array('1' => '', '', '','');
    $selt = $sel;
    $sel[$this->order] = 'selected="selected"';
    $selt[$this->orderT] = 'checked="checked"';
echo '<h3>' . $t->_('ordinamento dei villaggi') . '</h3>
        ordine
        <select name="order" onchange="ev.hideopt(this.value)">
        <option value="1" ' . $sel[1] . '>'.$t->_("di fondazione").'</option>
        <option value="2" ' . $sel[2] . '>'.$t->_("alfabetico").'</option>
        <option value="3" ' . $sel[3] . '>'.$t->_("distanza").'</option>
		<option value="4" ' . $sel[4] . '>'.$t->_("personalizzato").'</option>
        <option value="5" ' . $sel[5] . '>'.$t->_("POP").'</option>
        </select>
	<span id="opt1" '.($sel[3] ? 'style="display:none"' : '').'>
        <input name="orderT" class="opt1" type="radio" value="0" ' . $selt[0] . ' />' . $t->_('ascendente') . '
        <input name="orderT" class="opt1" type="radio" value="1" ' . $selt[1] . ' />' . $t->_('descendente').'
	</span>
	<span id="opt2" '.(!$sel[3] ? 'style="display:none"' : '').'>
	<input onchange="ev.disableinput(this.checked)" type="checkbox" name="coordB" value="1" '.($this->coordB ? 'checked="checked"' : '').' />
	<input class="opt2" '.(!$this->coordB ? 'disabled="disabled"' : '').' size="3" name="x" maxlength="3" value="'.$this->x.'" /> |
	<input class="opt2" '.(!$this->coordB ? 'disabled="disabled"' : '').' size="3" name="y" maxlength="3" value="'.$this->y.'" />
	</span>';

    //news letter
    echo '<h3>' . $t->_('News letter') . '</h3>
        voglio ricevere informazioni sugli aggiornamenti di evolution per email
        <input name="news" type="checkbox" value="1" '.($this->news ? 'checked="checked"' : '' ).'/>';

?>

<h3><?php echo $t->_('cancella account');?></h3>
        <p><input disabled="disabled" name="del_user" value="true" type="checkbox" onclick="if (this.checked) this.checked=confirm('<?php 
            echo $t->_('sei sicuro');
            ?>?')" /></p>
        <?php echo $t->_("inserisci password");?>
	<input disabled="disabled" name="pass" size="7" type="password" />
	
	<input type="submit" value="<?php echo $t->_("salva");?>" name="submit" />

</form>*/