{"html":
<?php 

//$update=Model_civilta::getInstance()->refresh->getdata();
$update=Model_refresh::getInstance();
$title=$this->headTitle()->toString();
$title=str_replace("<title>", "", $title);
$title=str_replace("</title>", "", $title);
//preparazione truppe
$t=Zend_Registry::get("translate");
$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
if ($update->displaytroops) {
		global $NameTroops;
		$text= '<h3><a href="'.$this->baseUrl().'/'.$module.'/movements">
		' . $t->_('TRUPPE PRESENTI') . '</a>
		</h3><div style="padding-left: 10px;padding-right: 10px;">
                <ul style="padding-left: 0px;">';
		for($i=0;$update->displaytroops[$i];$i++) {
			$text.= '<li style="list-style-type:none;">
			' . $this->image()->troop($update->displaytroops[$i]['trooper_id']) . '
					 ' . $update->displaytroops[$i]['numbers'] . '</li>';
		}
		$text.= '</ul></div>';
		$this->headScript()->captureStart();
		echo '$( "#troopers" ).accordion("destroy");
		$( "#troopers" ).accordion({
		active: false ,
		collapsible: true
	});';
		$this->headScript()->captureEnd();
}
$update->addIds("troopers", $text);
if ($update->getjs()) {
	$this->headScript()->captureStart();
	echo $update->getjs();
	$this->headScript()->captureEnd();
}
$update=$update->getdata();
$script=$this->headScript()->toString();
$script=str_replace('<script type="text/javascript">', "", $script);
$script=str_replace('</script>', "", $script);
$script=str_replace('//<!--', "", $script);
$script=str_replace('//-->', "", $script);
global $epflag;
if ($epflag) {
	$script.="$.ajax({url:path+'/'+module+'/processing',timeout:5000});";
}

if ($this->layout()->content) echo json_encode(array('text'=>$this->layout()->content,'title'=>$title,
'notdestroy'=>$this->layout()->notdetroy,'close'=>$this->layout()->close,
'x'=>$this->layout()->x,'y'=>$this->layout()->y,'mod'=>$this->layout()->mod,'id'=>$this->layout()->id));
else echo "false";?>,
"data":<?php echo json_encode($this->layout()->data);?>,"update":<?php echo json_encode($update);?>,
"javascript":<?php echo json_encode($script);?>}