<?php
//init
header('Content-Type:text/html; charset=UTF-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Age of Evolution');
$auth = Zend_Auth::getInstance();
$t = Zend_Registry::get("translate");
$req = Zend_Controller_Front::getInstance()->getRequest();
$module = $req->getModuleName();
$action = $req->getActionName();
$controller = $req->getControllerName();
$acl = Zend_Registry::get("acl");
$log = Zend_Registry::get("log");
$alerts = false;
if ($auth->hasIdentity()) {
    $alerts = Zend_Db_Table::getDefaultAdapter()->fetchAll(
    "SELECT * 
	FROM `" . ALERTS_TABLE .
     "` 
	WHERE `aid`!=ALL (
        SELECT `id` FROM `" .
     ALERTS_READ . "` WHERE `user`='" . $auth->getIdentity()->user_id . "'
    )");
}
if (! $alerts)
    $alerts[0] = false;
$nav = array('Home' => array('url' => '', 'img' => '/common/images/home.png'), 
'Forum' => array('url' => 'forum/', 'img' => '/common/images/forum.ico'), 
'Wiki' => array('url' => 'wiki/', 'img' => '/common/images/wiki-icon.png'));
if ($auth->hasIdentity()) {
    $nav['account'] = array('url' => 'account', 
    'img' => '/common/images/modacc.png');
    $nav['logout'] = array('url' => 'login/logout', 
    'img' => '/common/images/logout.png');
    $bug = $t->_('Segnalaci un bug o un tuo parere');
    $nav[$bug] = array('url' => 'ev.bugreport();', 
    'img' => '/common/images/bug.png', 'js' => true);
} else {
    $nav['Login'] = array('url' => 'login', 'img' => '/common/images/login.gif');
    $reg = $t->_('registrati');
    $nav[$reg] = array('url' => 'reg', 'img' => '/common/images/add.png');
}
if (is_array($this->layout()->nav)) {
    $nav = array_merge($nav, $this->layout()->nav);
}
$nav['Help'] = array('url' => 'ev.help(\'index\');', 
'img' => '/common/images/help.png', 'js' => true);
if ($acl->isAllowed(Model_role::getRole(), 'admin')) {
    $nav['Admin'] = array('url' => 'admin','img'=>'/common/images/village/corona.gif');
}
if ($module == "admin") {
    $nav['mkdata'] = array('url' => 'admin/mkdata');
    $nav['alerts'] = array('url' => 'admin/alerts');
    $nav['track'] = array('url' => 'admin/track');
    $man = $t->_('genera mappa');
    $nav[$man] = array('url' => 'admin/generate');
    $man = $t->_('manutenzione');
    $nav[$man] = array('url' => 'admin/maintenance');
    $nav['faq'] = array('url' => 'admin/faq');
}
//feed 
$ev = $config = Zend_Registry::get('config');
if ($ev->local) $news='<li>le news non funzionano in locale</li>';
else{
	try {
    	$feed =Zend_Feed::import('http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/feed/');
	} catch (Zend_Feed_Exception $e) {
    // feed import failed
   		$feed=array();
	}
	$news="";
// Loop over each channel item and store relevant data
	foreach ($feed as $item) {
		$date=new DateTime($item->pubDate());
		$news.='<li><span>'.$date->format("d/m/Y").'</span> <a href="'.$item->link().'">'.$item->title().'</a></li>';
	}
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="DESCRIPTION" content="browser game gratuito, gestionale in cui i giocatori comandano civiltà, portandole ad evolversi dalla preistoria fino al futuro" />
		<meta name="KEYWORDS" content="browsergame,strategia,gestionale,evoluzione,gratis" />
		<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />	
<?php
		echo $this->headLink()->prependStylesheet(
		$this->baseUrl() . '/common/css/css.php');
		$this->headScript()->captureStart();
//log
		if ($this->logger) {
			$text="";
			foreach ($this->logger as $value) {
				$text.="console.log(".($value['info'] ? "'".$value['info']."'," : "")."'".$value['timestamp']."',".$value['message'].",'".$value['priorityName']."');";
			}
			//$text.="</ol>";
		}
		?>

$(document).ready(function(){
	<?php echo $text;?>
    //***************************controllo aggiornamento script
    if (ev.revision<67) {
	    if (confirm('<?php echo $t->_('alcuni file (.js /.css) sono stati aggiornati, ma nel suo pc è presente una versione vecchia. la pagina verrà ricaricata per aggiornare la cache.');?>'))
	    	location.reload();
    }
	$("ul#news").liScroll();
	$("[title]:not(.context-menu div)").tooltip({
		   offset: [-10, 0],
		   delay:1,
		   predelay:400
		}).dynamic({ bottom: { direction: 'down'} });
	counter();
	$('input:submit,input:button,button:not(.img)').button();
	$(".password").keyup(function(){
		ev.ctrlpass();
	});
	$(".email").change(function() {
		ev.ctrlemail(this);
	});
	$(".number").keyup(function(){
		ev.ctrlnum(this);
	});
	setTimeout(ev.showalert,3000);
	ev.alertstak=<?php echo json_encode($alerts);?>;
	<?php
	if ($auth->hasIdentity()) {
    	$cat = Zend_Db_Table::getDefaultAdapter()->fetchAll("SELECT * FROM `site_track_cat`");
    foreach ($cat as $value) {
        $cate .= '<option value="' . $value['id'] . '" title="' .
         $value['description'] . '">' . $value['name'] . '</option>';
    }
    $content = array('title' => $t->_('bugreport'), 
    'text' => ('
<div id="report"></div>
<div id="form">
	<div id="type">
		<input type="radio" id="type1" name="type" checked="checked" value="bug" /><label for="type1">' .
     $this->image('/common/images/bug.png', 'bug', null, 32, 32) .
     '</label>
		<input type="radio" id="type2" name="type"  value="idea" /><label for="type2">' .
     $this->image('/common/images/idea.gif', $t->_('idee'), null, 32, 32) .
     '</label>
		<input type="radio" id="type3" name="type" value="notlike" /><label for="type3">' .
     $this->image('/common/images/notlike.gif', $t->_('lamentele'), null, 32, 
    32) . '</label>
	</div>
	<div>
		<select id="category">' . $cate .
     '</select>
	</div>
	<div>tags : <span id="itag"></span> <input id="tag" />
	<button onclick="ev.addtag($(\'#tag\').val());">' .
     $t->_('inserisci/elimina') .
     '</button></div>
	<textarea cols="42" rows="14" style="border:1px solid black;" id="description">' . $t->_(
    'descrivi qui il bug che hai trovato, un idea per migliorare il gioco o quello che non ti piace.
	cerca di essere chiaro e di compilare bene il form') .
     '</textarea>
	<div>' .
     $t->_(
    'se vuoi inviarci immagini caricale su un host online e metti qui l&apos;indirizzo') .
     '</div>
	<div><input id="link" /></div>
	<div style="float: right;"><button onclick="ev.sendbug()">' .
     $t->_('invia') . '</button></div>
</div><script type="text/javascript">$("#type").buttonset();$("button").button();
$(function() {
var cache = {},
lastXhr;
$( "#tag" ).autocomplete({
minLength: 1,
source: function( request, response ) {
var term = request.term;
if ( term in cache ) {
response( cache[ term ] );
return;
}
lastXhr = $.getJSON( path+"/track/auto", request, function( data, status, xhr ) {
cache[ term ] = data;
if ( xhr === lastXhr ) {
response( data );
}
});
}
});
});
	</' . 'script>'));
    echo 'ev.bugcontent=' . json_encode($content) . ';';
}
?>
});
var path='<?php echo $this->baseUrl();?>';
var module='<?php echo $module; ?>';
ev.parsedata({ alertstak:'<?php echo json_encode($alerts);?>'});

<?php
$this->headScript()->captureEnd();
		echo $this->headScript()->prependFile($this->baseUrl('/common/js/js.php'));

echo $this->headTitle();
?>
	</head>
	<body>
		<!-- SELECT LOCALE -->
		<div id="locale">
			language
			<form action="<?php echo $this->url();?>">
			<?php 
			$list=array_merge(array('browser'=>'auto'),$this->t->getList());
			echo $this->formSelect('locale',$_COOKIE['locale'],array('onchange'=>'submit();','id'=>'loc'),$list);
			?>
			</form>
		</div>
		<div id="container">
			<div id="load"></div>
			<div id="top">
				<table>
					<tr>
						<td style="width: 20%;"><?php echo $this->partial('right.phtml');?></td>
						<td style="width: 20%;"> <?php
							echo '<span id="timestamp" style="display:none">' . mktime() .'000</span>' .
 								$t->_("Ora del server") . ': <br/><span id="timedisp">' . date("d/m/Y H:i:s") .'</span>';?>
 						</td>
						<td style="width: 30%;">
							<div id="navigation">
<?php 					
/*
$page=array(
			array('label'=>'Home'
				,'module'=>'default'
				,'controller' => 'index'
				,'action'=>'index'
				,'order'=>0
			)
			,array('label'=>'Login'
				,'module'=>'default'
				,'controller' => 'login'
				,'action'=>'index'
				,'order'=>1
				,'resource'=>'login'
				,'privilege'=>'index'
			)
			,array('label'=>'Logout'
				,'module'=>'default'
				,'controller' => 'login'
				,'action'=>'logout'
				,'order'=>2
				,'resource'=>'login'
				,'privilege'=>'logout'
			)
			,array('label'=>'[REG]'
				,'module'=>'default'
				,'controller' => 'reg'
				,'action'=>'index'
				,'order'=>3
				,'resource'=>'reg'
				,'privilege'=>'index'
			)
			,array('label'=>'[PROFILE]'
					,'module'=>'default'
					,'controller' => 'profile'
					,'action'=>'index'
					,'order'=>4
					,'resource'=>'profile'
			)
			,array('label'=>'Credits'
				,'module'=>'default'
				,'controller' => 'index'
				,'action'=>'credits'
				,'order'=>100
			)
		);
		$menu=new Zend_Navigation($page);
		$acl = Zend_Registry::get("acl");
		
		$this->navigation($menu)->setAcl($acl)->setRole(Model_Role::getRole());
		echo $this->navigation();//->menu();*/		

echo $this->myMenu($nav);?>							
							</div>
						</td>
						<td style="width: 30%;"> <?php echo '<ul id="news"><li><span>AGE OF EVOLUTION</span><a href="http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/">News</a></li>'.$news.'</ul>';?> </td>
					</tr>
				</table>
			</div>
			<div id="sinistra">
<?php
if (! $ev->local) {
/*/pubblicità adsense
echo '
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2668371131665980";
// banner_dx 
google_ad_slot = "3462675419";
google_ad_width = 120;
google_ad_height = 600;
//-->
</script> <script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>';
// altervista */

echo "<script type=\"text/javascript\">
/* <![CDATA[ */
document.write('<s'+'cript type=\"text/javascript\" src=\"http://ad.altervista.org/js.ad/size=120X600/r='+new Date().getTime()+'\"><\/s'+'cript>');
/* ]]> */
</script>";

}
?>
			</div>
			<div id="content">      
<?php 			echo $this->layout()->content;?>
			</div>
		</div>   
<?php 	echo $this->partial('footer.phtml');?> 
	</body>
</html>