<?php 
if (!$this->flag) {
?>
<script type="text/javascript">
<!--

$(function() {
	$("#progresbar").progressbar({
		value: <?php echo $this->value;?>});
});
ev.time=2000;
function refreshbar() {
	ev.request('admin/index/loader','post',{flag:1},function(data){
		if (data.data[0]>0) {
			$("#progresbar").progressbar("value",data.data[0]);
			perc=$("#progresbar div").text();
			perc=perc.substr(0,perc.indexOf('%')-1);
		//alert(perc+'time '+ev.time+' data '+data.data);
			if ((perc>=data.data[0])&&(ev.time<=300000)) ev.time*=2;
			else {if ((perc<data.data[0])&&(ev.time>2000)) ev.time/=2;}
			$("#progresbar div").text(data.data[0]+"%"+data.data[1]);
			}
			//if (data.data[0]<100) setTimeout(refreshbar,ev.time);
			//else {
				//$("#image").attr("src","<?php echo $this->baseUrl();?>/admin/generate/image");
			//}
		
	});
}

//-->
</script>
<div id="progresbar">
</div>

<button onclick="ev.request('admin/generate/map','post');refreshbar()">esegui</button>
<button onclick="refreshbar();$('#image').attr('src','');$('#image').attr('src','<?php echo $this->baseUrl("admin/generate/image");?>');">image refresh</button>
<button id="apply" onclick="ev.request('admin/generate/apply','post');refreshbar()" >applica</button>
<div><img id="image" src="" alt="loading..."></div>
<?php 
}
else {
echo json_encode(array('data'=>array($this->value,$this->comment),'html'=>false,'update'=>false,'javascript'=>false));
}
?>
