<?php 
$update=Model_refresh::getInstance();
$module=Zend_Controller_Front::getInstance()->getRequest()->getModuleName();
//retrive a title
$title=$this->headTitle()->toString();
$title=str_replace("<title>", "", $title);
$title=str_replace("</title>", "", $title);
//preparazione truppe
if ($update->displaytroops) {//@todo rifare
		global $NameTroops;
		$text= '<h3><a href="'.$this->baseUrl().'/'.$module.'/movements">
		' . $t->_('TRUPPE PRESENTI') . '</a>
		</h3><div style="padding-left: 10px;padding-right: 10px;">
                <ul style="padding-left: 0px;">';
		for($i=0;$update->displaytroops[$i];$i++) {
			$text.= '<li style="list-style-type:none;">
			' . $this->image()->troop($update->displaytroops[$i]['trooper_id']) . '
					 ' . $update->displaytroops[$i]['numbers'] . '</li>';
		}
		$text.= '</ul></div>';
		$this->headScript()->captureStart();
		echo '$( "#troopers" ).accordion("destroy");
		$( "#troopers" ).accordion({
		active: false ,
		collapsible: true
	});';
		$this->headScript()->captureEnd();
}
$update->addIds("troopers", $text);
//preparazione javascript
if ($update->getjs()) {
	$this->headScript()->captureStart();
	echo $update->getjs();
	$this->headScript()->captureEnd();
}
$script=$this->headScript()->toString();
$script=str_replace('<script type="text/javascript">', "", $script);
$script=str_replace('</script>', "", $script);
$script=str_replace('//<!--', "", $script);
$script=str_replace('//-->', "", $script);
//if Event Processor stop.
global $epflag;
if ($epflag) {
	$script.="$.ajax({url:path+'/'+module+'/processing',timeout:5000});";
}
$update=$update->getdata();
//content is display on window
if ($this->layout()->content) $this->key['HTML']=json_encode(array('text'=>$this->layout()->content,'title'=>$title,
'notdestroy'=>$this->layout()->notdetroy,'close'=>$this->layout()->close,
'x'=>$this->layout()->x,'y'=>$this->layout()->y,'mod'=>$this->layout()->mod,'id'=>$this->layout()->id,'button'=>$this->layout()->button,'error'=>$this->layout()->error));
else $this->key['HTML']="false";
$this->key['DATA']=json_encode($this->layout()->data);
$this->key["UPDATE"]=json_encode($update);
$this->key["JAVASCRIPT"]=json_encode($script);
Zend_View_Filter_Tmpeng::addkey($this->key);
?>
{"html":HTML,"data":DATA,"update":UPDATE,"javascript":JAVASCRIPT}
