<?php
//risuluzione ottimale 1280x1024
//init

$acl=Zend_Registry::get("acl");
$log=Zend_Registry::get("log");
$x="0";$y="0";
if ($this->auth->hasIdentity()) {
	$civ=Model_civilta::getInstance();
	$x=$civ->village->data[$civ->getCurrentVillage()]['x'];
	$y=$civ->village->data[$civ->getCurrentVillage()]['y'];
}
$iconSize=16;
$this->myMenu() 
	->add('[PROFILE]',"javascript:$('#profile').dialog('open');",null,null,8,'account',null,$this->path.'/common/images/pannello_utente.png',$iconSize,false)
	->add('[CITY]',"javascript:ev.request('".$this->module."/index/village','post',{ajax:1});",null,null,9,null,null,$this->path.'/common/images/city.png',$iconSize,false)
	->add('[MAP]',$this->module,null,null,10,null,null,$this->path.'/common/images/mappa.gif',$iconSize,false)
	->add('Report',"javascript:ev.request('".$this->module."/report','post',{ajax:1});",null,null,11,null,null,$this->path.'/common/images/report1.gif',$iconSize,false)
	->add('[MESSAGES]',"javascript:ev.request('".$this->module."/message','post',{ajax:1});",null,null,12,null,null,$this->path.'/common/images/mess_read0.gif',$iconSize,false)
	->add('[TOP]',"javascript:ev.request('".$this->module."/top','post',{ajax:1});",null,null,13,null,null,$this->path.'/common/images/top.png',$iconSize,false)
	->add('Debug',$this->module,'debug',null,14,null,null,$this->path.'/common/images/tool.gif',$iconSize,false)
	;
	

 $width=$this->myMenu()->getPageCount()*28;

?>
		<div id="sinistra">
<?php
//banner

if (!$this->ev->local) {
/*/ adsense
    echo '<script type="text/javascript"><!--
google_ad_client = "ca-pub-2668371131665980";
// header game 
google_ad_slot = "8866943812";
google_ad_width = 728;
google_ad_height = 90;
//-->
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>';
// av */
echo "<script type=\"text/javascript\">
/* <![CDATA[ */
document.write('<s'+'cript type=\"text/javascript\" src=\"http://ad.altervista.org/js.ad/size=728X90/r='+new Date().getTime()+'\"><\/s'+'cript>');
/* ]]> */
</script>";
}
?>

		</div>
		
			<div id="movemap" <?php 
if ($_COOKIE['right_pannel']=='true') {
	echo 'style="display:none;"';
}?> >
				<center style="padding:4px;" class="ui-state-default" onmouseover="$(this).removeClass('ui-state-default').addClass('ui-state-hover');" 
				onmouseout="$(this).removeClass('ui-state-hover').addClass('ui-state-default');" 
				onmousedown="$(this).removeClass('ui-state-hover').addClass('ui-state-active');" 
				onmouseup="$(this).removeClass('ui-state-active').addClass('ui-state-default');"><img src="<?php echo $this->baseUrl();?>/common/images/void.png" onclick="$('#nav_pannel').toggle('blind', null,500);p=$.cookie('nav_pannel')=='true';$.cookie('nav_pannel',!p,{path:'/',expires:1});" class="ui-state-default ui-icon ui-icon-grip-dotted-horizontal ui-corner-all" /></center>
				<div id="nav_pannel"><div id="navpad">
					<center>
					<img id="minimap" height="100" width="100" alt="minimap" src="" />
					</center>
					<div id="freccia_su" class="arrow_up" onclick="ev.map.arrow('up')"></div>
					<div id="freccia_sx" class="arrow_sx" onclick="ev.map.arrow('left')"></div>
					<div id="freccia_giu" class="arrow_down" onclick="ev.map.arrow('down')"></div>
					<div id="freccia_dx" class="arrow_dx" onclick="ev.map.arrow('right')"></div>
				</div>
				<input id="x" class="number" size="3" maxlength="4" /> | <input id="y" class="number" size="3" maxlength="4" /> <button onclick="ev.map.position($('#x').val(),$('#y').val() );">OK</button>
				</div>
			</div>
			<div id="destra">
				
				<div id="right" <?php 
if ($_COOKIE['right_pannel']=='true') {
	echo 'style="display:none;"';
}
$log->debug($_COOKIE);
?>><?php echo $this->partial('right.phtml');?></div>
				<center class="ui-state-default" onmouseover="$(this).removeClass('ui-state-default').addClass('ui-state-hover');" 
				onmouseout="$(this).removeClass('ui-state-hover').addClass('ui-state-default');" 
				onmousedown="$(this).removeClass('ui-state-hover').addClass('ui-state-active');" 
				onmouseup="$(this).removeClass('ui-state-active').addClass('ui-state-default');"><img src="<?php echo $this->baseUrl();?>/common/images/void.png" onclick="$('#right').toggle('blind',null,500);p=$.cookie('right_pannel')=='true';$.cookie('right_pannel',!p,{path:'/',expires:1});" class="ui-state-default ui-icon ui-icon-grip-dotted-horizontal ui-corner-all" /></center>
			</div>
			
			<div id="load"></div>
        	<div id="navigation" style="width:<?php echo $width;?>px;">
<?php 		echo $this->myMenu(); ?>	
			</div>
	