<!-- SELECT LOCALE -->
		<div id="locale">
			language
			<form action="<?php echo $this->url();?>">
			<?php 
			$list=array_merge(array('browser'=>'auto'),$this->t->getList());
			echo $this->formSelect('locale',$_COOKIE['locale'],array('onchange'=>'submit();','id'=>'loc'),$list);
			?>
			</form>
		</div>
<div id="top">
				<table>
					<tr>
						<td style="width: 20%;"><?php $db = Zend_Db_Table::getDefaultAdapter();
						echo '<div style="padding-left: 20px;" ><b>[TOTALUSER]</b>
                    '. $db->fetchOne(
    "SELECT count(*) FROM `" . USERS_TABLE . "`") . "<br/>
                        <b>[USERONLINE]</b> " . intval(
    $db->fetchOne(
    "SELECT count(*) 
			FROM `" . SESSIONS_TABLE . "` 
			 WHERE `validate`='1' 
			 AND `last_activity`>'" . (mktime() - 900) . "' 
			 AND `user_id` != '0'")) . '</div>';?></td>
						<td style="width: 20%;"> <?php
							echo $this->servertime;?>
 						</td>
						<td style="width: 30%;">
							<div id="navigation">
<?php 							echo $this->myMenu();?>							
							</div>
						</td>
						<td style="width: 30%;"> <?php echo '<ul id="news"><li><span>AGE OF EVOLUTION</span><a href="http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/">News</a></li>'.$news.'</ul>';?> </td>
					</tr>
				</table>
			</div>
			