<?php
/**
 * @todo aggiungere finestra account. rendere il login e la registrazione ajax.
 * @todo usare un solo layout e discriminare qui i vari parziali da usare
 */
//init
header('Content-Type:text/html; charset=UTF-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Age of Evolution');
//init variable
$auth = Zend_Auth::getInstance();
$req = Zend_Controller_Front::getInstance()->getRequest();
$module = $req->getModuleName();
$action = $req->getActionName();
$controller = $req->getControllerName();
$alerts = false;
if ($auth->hasIdentity()) {
    $alerts=Model_alerts::getAlerts();
}
if (! $alerts)
    $alerts[0] = false;
//$menu=new Zend_View_Helper_MyMenu();
//*******************************************init menu
$iconSize=16;
$path=$this->baseUrl();
$this->myMenu()
	->add('Home','default','index','index',1,null,null,$path.'/common/images/home.png',$iconSize,false)
	->add('Forum','forum',null,null,2,null,null,$path.'/common/images/forum.ico',$iconSize,false)
	->add('Wiki','wiki',null,null,3,null,null,$path.'/common/images/wiki-icon.png',$iconSize,false)
	->add('Login',"javascript:$('#login').dialog('open');",null,null,4,'login','index',$path.'/common/images/login.gif',$iconSize,false)
	->add('[REG]',"javascript:$('#reg').dialog('open');",null,null,5,'reg','index',$path.'/common/images/add.png',$iconSize,false)
	->add('Logout','javascript:ev.logout();','','',6,'login','logout',$path.'/common/images/logout.png',$iconSize,false)
	->add('[PROFILE]','default','account','index',7,'account',null,$path.'/common/images/modacc.png',$iconSize,false)
	->add('[BUG]','javascript:ev.bugreport();',null,null,20,'priv_zone',null,$path.'/common/images/bug.png',$iconSize,false)
	->add(array('label'=>'Admin'
			,'module'=>'admin'
			//,'controller'=>'index'
			//,'action'=>'index'
			,'order'=>100
			,'resource'=>'admin'
			,'icon'=>$path.'/common/images/village/corona.gif'
			,'iconSize'=>$iconSize
			,'text'=>false
		)
	)
	->add('Help',"javascript:ev.help('index');",null,null,99,null,null,$path.'/common/images/help.png',$iconSize,false);

if ($module=='admin') {
	$this->myMenu()->add(array('label'=>'[MKDATA]'
					,'module'=>'admin'
					,'controller'=>'mkdata'
					,'order'=>8
					,'resource'=>'admin'
	))->add(array('label'=>'[ALERTS]'
					,'module'=>'admin'
					,'controller'=>'track'
					,'order'=>9
					,'resource'=>'admin'
	))->add(array('label'=>'[MAP]'
					,'module'=>'admin'
					,'controller'=>'generate'
					,'order'=>10
					,'resource'=>'admin'
	))->add(array('label'=>'[MAINTENAINCE]'
					,'module'=>'admin'
					,'controller'=>'maintenance'
					,'order'=>11
					,'resource'=>'admin'
	))->add(array('label'=>'F.a.q'
					,'module'=>'admin'
					,'controller'=>'faq'
					,'order'=>12
					,'resource'=>'admin'
	));
}

//feed 
$ev = $config = Zend_Registry::get('config');
if ($ev->local) $news='<li>le news non funzionano in locale</li>';
else{
	try {
    	$feed =Zend_Feed::import('http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/feed/');
	} catch (Zend_Feed_Exception $e) {
    // feed import failed
   		$feed=array();
	}
	$news="";
// Loop over each channel item and store relevant data
	foreach ($feed as $item) {
		$date=new DateTime($item->pubDate());
		$news.='<li><span>'.$date->format("d/m/Y").'</span> <a href="'.$item->link().'">'.$item->title().'</a></li>';
	}
}

?>
<!DOCTYPE HTML>
<html>
	<head>
		<meta name="DESCRIPTION" content="browser game gratuito, gestionale in cui i giocatori comandano civiltà, portandole ad evolversi dalla preistoria fino al futuro" />
		<meta name="KEYWORDS" content="browsergame,strategia,gestionale,evoluzione,gratis" />
		<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />	
<?php
		echo $this->headLink()->prependStylesheet(
		$this->baseUrl() . '/common/css/css.php');
echo $this->headScript()->prependFile($this->baseUrl('js'));
?>
<script type="text/javascript">
<!--
//******************************************logger*******************************************************
<?php

		if ($logmess=Plugin_Logweb::get()) {
			foreach ($logmess as $log) {
				echo 'console.log("'.$log['timestamp'].' - '.$log['priorityName'].' - '.($log['info']? $log[info].': ' : '').'",'.$log['message'].');';
			}
		}
?>
	$(document).ready(function(){
		//add button
		$("button:not(.server):not(.close):not(.edit):not(.add):not(.delete),input[type=submit]:not(.edit):not(.add):not(.delete)").button();
		$("button.edit").button({icons: {
	        primary: "ui-icon-wrench"
	    },
	    text: false
	    });
		$("button.close").button({icons: {
	        primary: "ui-icon-circle-close"
	    },
	    text: false
	    });
		$("button.add").button({icons: {
	        primary: "ui-icon-plus"
	    },
	    text: false
	    });
		$("button.delete").button({icons: {
	        	primary: "ui-icon-close"
	    	},
	    		text: false
	    });;
	    $("#loginForm").submit(function(e) {
		    ev.login();
		    e.preventDefault();
		    return false;
	    });
//windows
		$("#credits").dialog({autoOpen: false});
		<?php 
	if ($module=='default') {
		echo '$("#reg").dialog({autoOpen: false});$("#login").dialog({autoOpen: false});';
		if (APPLICATION_ENV=='production') echo '$(document).ready(function() {
		
		//$("#recaptcha_switch_audio_btn").remove();
		Recaptcha.switch_type=function(){ alert("audio disabilitato!");};
		
		}); ';
	}
	?>
	//***************************controllo aggiornamento script
    if (ev.revision<<?php echo REVISION;?>) {
	    if (confirm('<?php echo $this->t->_('alcuni file (.js /.css) sono stati aggiornati, ma nel suo pc è presente una versione vecchia. la pagina verrà ricaricata per aggiornare la cache.');?>'))
	    	location.reload();
    }
	$("ul#news").liScroll();
	$("[title]:not(.context-menu div)").tooltip({
		   offset: [-10, 0],
		   delay:1,
		   predelay:400
		}).dynamic({ bottom: { direction: 'down'} });
	counter();
	$('input:submit,input:button,button:not(.img)').button();
	$(".password").keyup(function(){
		ev.ctrlpass();
	});
	$(".email").change(function() {
		ev.ctrlemail(this);
	});
	$(".number").keyup(function(){
		ev.ctrlnum(this);
	});
	setTimeout(ev.showalert,3000);
	ev.alertstak=<?php echo json_encode($alerts);?>;
	<?php
			if ($auth->hasIdentity()) {
		    	$cat = Zend_Db_Table::getDefaultAdapter()->fetchAll("SELECT * FROM `site_track_cat`");
		    foreach ($cat as $value) {
		        $cate .= '<option value="' . $value['id'] . '" title="' .
		         $value['description'] . '">' . $value['name'] . '</option>';
		    }
		    $content = array('title' => '[bugreport]', 
		    'text' => ('
		<div id="report"></div>
		<div id="form">
			<div id="type">
				<input type="radio" id="type1" name="type" checked="checked" value="bug" /><label for="type1">' .
		     $this->image('/common/images/bug.png', 'bug', null, 32, 32) .
		     '</label>
				<input type="radio" id="type2" name="type"  value="idea" /><label for="type2">' .
		     $this->image('/common/images/idea.gif', '[idee]', null, 32, 32) .
		     '</label>
				<input type="radio" id="type3" name="type" value="notlike" /><label for="type3">' .
		     $this->image('/common/images/notlike.gif', '[lamentele]', null, 32, 
		    32) . '</label>
			</div>
			<div>
				<select id="category">' . $cate .
		     '</select>
			</div>
			<div>tags : <span id="itag"></span> <input id="tag" />
			<button onclick="ev.addtag($(\'#tag\').val());">' .
		     '[inserisci/elimina]' .
		     '</button></div>
			<textarea cols="42" rows="14" style="border:1px solid black;" id="description">' . 
		    '[descrivi qui il bug che hai trovato, un idea per migliorare il gioco o quello che non ti piace.
			cerca di essere chiaro e di compilare bene il form]' .
		     '</textarea>
			<div>' .
		     
		    '[se vuoi inviarci immagini caricale su un host online e metti qui l&apos;indirizzo]' .
		     '</div>
			<div><input id="link" /></div>
			<div style="float: right;"><button onclick="ev.sendbug()">' .
		     '[invia]' . '</button></div>
		</div><script type="text/javascript">$("#type").buttonset();$("button").button();
		$(function() {
		var cache = {},
		lastXhr;
		$( "#tag" ).autocomplete({
		minLength: 1,
		source: function( request, response ) {
		var term = request.term;
		if ( term in cache ) {
		response( cache[ term ] );
		return;
		}
		lastXhr = $.getJSON( path+"/track/auto", request, function( data, status, xhr ) {
		cache[ term ] = data;
		if ( xhr === lastXhr ) {
		response( data );
		}
		});
		}
		});
		});
			</' . 'script>'));
		    echo 'ev.bugcontent=' . json_encode($content) . ';';
		}
		?>
		   
	
});
var path='<?php echo $this->baseUrl();?>';
var module='<?php echo $module; ?>';
ev.parsedata({ alertstak:'<?php echo json_encode($alerts);?>'});
//-->
</script>
<?php
echo $this->headTitle();
?>
	</head>
	<body>
		<!-- SELECT LOCALE -->
		<div id="locale">
			language
			<form action="<?php echo $this->url();?>">
			<?php 
			$list=array_merge(array('browser'=>'auto'),$this->t->getList());
			echo $this->formSelect('locale',$_COOKIE['locale'],array('onchange'=>'submit();','id'=>'loc'),$list);
			?>
			</form>
		</div>
		<div id="container">
			<div id="load"></div>
			<div id="top">
				<table>
					<tr>
						<td style="width: 20%;"><?php echo $this->partial('right.phtml');?></td>
						<td style="width: 20%;"> <?php
							echo '<span id="timestamp" style="display:none">' . mktime() .'000</span>' .
 								"[Ora del server]" . ': <br/><span id="timedisp">' . date("d/m/Y H:i:s") .'</span>';?>
 						</td>
						<td style="width: 30%;">
							<div id="navigation">
<?php 							echo $this->myMenu();?>							
							</div>
						</td>
						<td style="width: 30%;"> <?php echo '<ul id="news"><li><span>AGE OF EVOLUTION</span><a href="http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/">News</a></li>'.$news.'</ul>';?> </td>
					</tr>
				</table>
			</div>
			<div id="sinistra">
<?php
if (! $ev->local) {
/*/pubblicità adsense
echo '
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2668371131665980";
// banner_dx 
google_ad_slot = "3462675419";
google_ad_width = 120;
google_ad_height = 600;
//-->
</script> <script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>';
// altervista */

echo "<script type=\"text/javascript\">
/* <![CDATA[ */
document.write('<s'+'cript type=\"text/javascript\" src=\"http://ad.altervista.org/js.ad/size=120X600/r='+new Date().getTime()+'\"><\/s'+'cript>');
/* ]]> */
</script>";

}
?>
			</div>
			<div id="content">      
<?php 
echo $this->layout()->content;
?>
			</div>
		</div>
<?php 
if ($module=="default") {
	echo ' <div id="login" title="Login">';
	$login=new Form_LoginForm();
	//$login->setAction($this->url(array('controller'=>'login')));
	echo $login.'</div>
			<div id="reg" title="[REG]">';
	$reg=new Form_Register();
	$reg->setAction($this->url(array('controller'=>'reg')));
	echo $reg.'</div>';
}
?>
		
		<div id="credits">
<h3><a href="http://blogpagliaccio.wordpress.com" target="_blanc" >Pagliaccio</a></h3>
<p>
    Ideatore, amministratore e realizzatore del gioco. Programmatore php, javascript.
</p>
<h3><a href="http://leonardosite.altervista.org" target="_blanc" >Leonardo I</a></h3>
<p>
    Co-amministratore e realizzatore del gioco. Programmatore php, javascript.
</p>



<h3>ringraziamo i segunti tool per il supporto dato:</h3>

    <a href="http://validator.w3.org/check?uri=referer">
        <img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0 Transitional" height="31" width="88" />
    </a>

<a href="http://www.linux.org"><img src="<?php echo $this->baseUrl()?>/common/images/linux_icon.gif" alt="linux" height="60" width="65" /></a>
<a href="http://apache.org/"><img src="<?php echo $this->baseUrl()?>/common/images/apache_icon.gif" alt="apache" height="50" width="72" /></a>
<a href="http://www.mysql.it"><img src="<?php echo $this->baseUrl()?>/common/images/mysql_icon.gif" alt="mysql" height="37" width="63" /></a>
<a href="http://www.php.net"><img src="<?php echo $this->baseUrl()?>/common/images/php_icon.gif" alt="php" height="35" width="44" /></a>
<a href="http://www.zend.com/"><img src="<?php echo $this->baseUrl()?>/common/images/zend.png" alt="zend" height="50" width="50" /></a>

</div>
<?php 	echo $this->partial('footer.phtml');?> 
	</body>
</html>