<?php
//init
header('Content-Type:text/html; charset=UTF-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Age of Evolution');
//init variable
$this->auth = Zend_Auth::getInstance();
$req = Zend_Controller_Front::getInstance()->getRequest();
$this->module = $req->getModuleName();
$this->action = $req->getActionName();
$this->controller = $req->getControllerName();
$this->ev = $config = Zend_Registry::get('config');
$this->alerts = false;
/**
 * 
 * Enter description here ...
 * @var Zend_Acl
 */
$acl=Zend_Registry::get('acl');
if ($this->auth->hasIdentity()&& $this->game) {
	$age=Zend_Registry::get("age");
	$par = "&s=" . ($age + 1);
}
$this->servertime='<span id="timestamp" style="display:none">' . mktime() .'000</span>' .
"[SERVERTIME]" . ': '.($this->game? '' :'<br/>').'<span id="timedisp">' . date("d/m/Y H:i:s") .'</span>';
/**
 *
 * @var Zend_View
 */
$view=$this;
if ($this->auth->hasIdentity()) {
    $this->alerts=Model_alerts::getAlerts();
}
if (! $this->alerts)
    $this->alerts[0] = false;
//$menu=new Zend_View_Helper_MyMenu();
//*******************************************init menu
$iconSize=16;
$this->path=$this->baseUrl();
$this->myMenu()
	->add('Home','default','index','index',1,null,null,$this->path.'/common/images/home.png',$iconSize,false)
	->add('Forum','forum',null,null,2,null,null,$this->path.'/common/images/forum.ico',$iconSize,false)
	->add('Wiki','wiki',null,null,3,null,null,$this->path.'/common/images/wiki-icon.png',$iconSize,false)
	->add('Login',"javascript:$('#login').dialog('open');",null,null,4,'login','index',$this->path.'/common/images/login.gif',$iconSize,false)
	->add('[REG]',"javascript:$('#reg').dialog('open');",null,null,5,'reg','index',$this->path.'/common/images/add.png',$iconSize,false)
	->add('Logout','javascript:ev.logout();','','',6,'login','logout',$this->path.'/common/images/logout.png',$iconSize,false)
	->add('[ACCOUNT]',"javascript:$('#account').dialog('open');",null,null,7,'account',null,$this->path.'/common/images/modacc.png',$iconSize,false)
	->add('Feedback','javascript:ev.bugreport();',null,null,20,'priv_zone',null,$this->path.'/common/images/bug.png',$iconSize,false)
	->add(array('label'=>'Admin'
			,'module'=>'admin'
			//,'controller'=>'index'
			//,'action'=>'index'
			,'order'=>100
			,'resource'=>'admin'
			,'icon'=>$this->path.'/common/images/village/corona.gif'
			,'iconSize'=>$iconSize
			,'text'=>false
		)
	);

if ($this->module=='admin') {
	$this->myMenu()->add(array('label'=>'[MKDATA]'
					,'module'=>'admin'
					,'controller'=>'mkdata'
					,'order'=>8
					,'resource'=>'admin'
	))->add(array('label'=>'[ALERTS]'
					,'module'=>'admin'
					,'controller'=>'track'
					,'order'=>9
					,'resource'=>'admin'
	))->add(array('label'=>'[MAP]'
					,'module'=>'admin'
					,'controller'=>'generate'
					,'order'=>10
					,'resource'=>'admin'
	))->add(array('label'=>'[MAINTENAINCE]'
					,'module'=>'admin'
					,'controller'=>'maintenance'
					,'order'=>11
					,'resource'=>'admin'
	))->add(array('label'=>'F.a.q'
					,'module'=>'admin'
					,'controller'=>'faq'
					,'order'=>12
					,'resource'=>'admin'
	));
}

//feed 

if ($this->ev->local) $news='<li>le news non funzionano in locale</li>';
else{
	try {
    	$feed =Zend_Feed::import('http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/feed/');
	} catch (Zend_Feed_Exception $e) {
    // feed import failed
   		$feed=array();
	}
	$news="";
// Loop over each channel item and store relevant data
	foreach ($feed as $item) {
		$date=new DateTime($item->pubDate());
		$news.='<li><span>'.$date->format("d/m/Y").'</span> <a href="'.$item->link().'">'.$item->title().'</a></li>';
	}
}

?>
<!DOCTYPE HTML>
<html>
	<head>
		<meta name="DESCRIPTION" content="browser game gratuito, gestionale in cui i giocatori comandano civiltà, portandole ad evolversi dalla preistoria fino al futuro" />
		<meta name="KEYWORDS" content="browsergame,strategia,gestionale,evoluzione,gratis" />
		<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />	
<?php
// js e css script
		echo $this->headLink()->prependStylesheet(
		$this->baseUrl('css') .($this->game? '?l=g':'').($par?$par:''));
		echo $this->headStyle();
echo $this->headScript()->prependFile($this->baseUrl('js'));

$complete=new Form_Complete();
$ev=$complete->getElement("ev");
$select='<select>';
foreach ($ev->getMultiOptions() as $key => $value) {
	$select.='<option value="'.$key.'">'.$value.'</value>';
}
$select.='</select>';

?>
<script type="text/javascript">
<!--
var debugmenu=[
	       		{'riempi magazzini':{
	       				onclick:function(){
	       					ev.request(module+"/debug/fill","post",{ajax:1});
	       		    	}
	       			}
	       		},
	       		{'aggiorna produzione':{
	       				onclick:function (){
	       					ev.request(module+"/debug/aggprod","post",{ajax:1});
	       				}
	       			}
	       		},
	       		{'completa evento <?php echo $select; ?> <button>OK</button>':function(menuItem,cmenu,e) {
	       				$t=$(e.target);
	       				if ($t.is('button')) {
	       					$event=$(menuItem).find('select');
	       					ev.request(module+"/debug/complete","post",{ajax:1,ev:$event.val(),vid:'this'})
	       		            return true;
	       		        }
	       		        else return false;
	       			}
	       		},
	       		{'aggiungi 100 abitanti':{
	       				onclick:function (){
	       					ev.request(module+"/debug/addpop","post",{ajax:1});
	       				}
	       			}
	       		}
	];
$(document).ready(function(){
//******************************************logger*******************************************************
<?php

		if ($logmess=Plugin_Logweb::get()) {
			foreach ($logmess as $log) {
				echo 'console.log("'.$log['timestamp'].' - '.$log['priorityName'].' - '.($log['info']? $log[info].': ' : '').'",'.$log['message'].');';
			}
		}
	if ($this->module=='default') {
		echo '$("#reg").dialog({autoOpen: false});$("#login").dialog({autoOpen: false});';
		if (APPLICATION_ENV=='production') echo '$(document).ready(function() {
		
		//$("#recaptcha_switch_audio_btn").remove();
		Recaptcha.switch_type=function(){ alert("audio disabilitato!");};
		
		}); ';
	}
	?>
	//***************************controllo aggiornamento script
    if (ev.revision<<?php echo REVISION;?>) {
	    if (confirm('<?php echo $this->t->_('alcuni file (.js /.css) sono stati aggiornati, ma nel suo pc è presente una versione vecchia. la pagina verrà ricaricata per aggiornare la cache.');?>'))
	    	location.reload();
    }
	
	ev.alertstak=<?php echo json_encode($this->alerts);?>;
	<?php
			if ($this->auth->hasIdentity()) {
		    	$cat = Zend_Db_Table::getDefaultAdapter()->fetchAll("SELECT * FROM `site_track_cat`");
		    foreach ($cat as $value) {
		        $cate .= '<option value="' . $value['id'] . '" title="' .
		         $value['description'] . '">' . $value['name'] . '</option>';
		    }
		    $content = array('title' => 'Feedback', 
		    'text' => ('
		<div id="report"></div>
		<div id="form">
			<div id="type">
				<input type="radio" id="type1" name="type" checked="checked" value="bug" /><label for="type1">' .
		     $this->image('/common/images/bug.png', 'Bug', 'Bug', 32, 32) .
		     '</label>
				<input type="radio" id="type2" name="type"  value="idea" /><label for="type2">' .
		     $this->image('/common/images/idea.gif', '[IDEA]', '[IDEA]', 32, 32) .
		     '</label>
				<input type="radio" id="type3" name="type" value="notlike" /><label for="type3">' .
		     $this->image('/common/images/notlike.gif', '[NOTLIKE]', '[NOTLIKE]', 32, 
		    32) . '</label>
			</div>
			<div>[CATEGORY]
				<select id="category">' . $cate .
		     '</select>
			</div>
			<div title="[BUGTAG]">tags : <span id="itag"></span> <input id="tag"/>
			<button onclick="ev.addtag($(\'#tag\').val());">' .
		     '[INSERT]/[DELETE]' .
		     '</button></div>
			<textarea cols="42" rows="14" style="border:1px solid black;" id="description" placeholder="[BUGDESC]"></textarea>
			<div>Link:<input id="link"  placeholder="[BUGIMG]" /></div>
			<div style="float: right;"><button onclick="ev.sendbug()">' .
		     '[SEND]' . '</button></div>
		</div><script type="text/javascript">$("#type").buttonset();initbutton();
		$(function() {
		var cache = {},
		lastXhr;
		$( "#tag" ).autocomplete({
		minLength: 1,
		source: function( request, response ) {
		var term = request.term;
		if ( term in cache ) {
		response( cache[ term ] );
		return;
		}
		lastXhr = $.getJSON( path+"/track/auto", request, function( data, status, xhr ) {
		cache[ term ] = data;
		if ( xhr === lastXhr ) {
		response( data );
		}
		});
		}
		});
		});
			</' . 'script>'));
		    echo 'ev.bugcontent=' . json_encode($content) . ';';
		}
		?>
		   
	
});
var path='<?php echo $this->baseUrl();?>';
var module='<?php echo $this->module; ?>';
ev.parsedata({ alertstak:'<?php echo json_encode($this->alerts);?>'});
<?php
if ($this->game) {
	$civ=Model_civilta::getInstance();
	echo "ev.totpos".TOTBUILDING.";";
	global $Building_Array;
	echo "ev.classbuilding=".json_encode($Building_Array).";";
	?>
	ev.menubuilding=[{'[UPGRADE]':{onclick:ev.build.upgrade,icon:path+'/common/images/add.png'}},
		          {'[DESTROY]':{onclick:ev.build.destroy,icon:path+'/common/images/del.gif'}}];
	$(document).bind('quest',ev.quest.questhandler);
	$(document).ready(function(){
		<?php
		global $epflag;
		if ($epflag) echo "$.ajax({url:path+'/'+module+'/processing',timeout:5000});";
		
		
	if ((!$civ->quest->read)&&$canshow) {
			echo 'setTimeout(ev.quest.showquest,4000);';
		}
		
		?>
	});
	ev.age=<?php echo intval(( $civ ? $civ->getAge() : '0'));?>;
	ev.max=[<?php echo MAX_X;?>,<?php echo MAX_Y;?>];
	<?php if ($civ->data) { $id=$civ->village->data[$civ->getCurrentVillage()]['id'];
	$xy=Model_map::getInstance()->getCoordFromId($id);
	?>ev.focus.x=<?php echo intval($xy['x']);?>;
	ev.focus.y=<?php echo intval($xy['y']);?>;
	ev.focus.id=<?php echo intval($civ->getCurrentVillage());?>;
	ev.totpos=<?php echo intval(TOTBUILDING)?>;
	ev.civ=<?php echo json_encode($civ->data->toArray());?>;
	<?php }?>
	ev.quest.flagquest=<?php echo ($canshow? "true" : "false");?>;
	<?php 
}
?>
//-->
</script>
<?php
echo $this->headTitle();
?>
	</head>
	<body>
	<?php 
	$banner='<div id="banner">';
	if (!$this->ev->local) {//banner
	}
	if ($this->game) {
		$banner.='<div id="hidad"><a href="#">[HIDE]</a></div>';
	}
	$banner.='</div>';
	$nobanner=$acl->isAllowed(Model_role::getRole(),'nobanner');
	if ($this->game && !$nobanner) echo $banner;
	?>
		<div id="container">
			<?php 
			if (!$this->game && !$nobanner) echo $banner;
			?>
		
			<div id="load"></div>
			
			<?php 
			
			if ($this->game) {
				echo $view->render('game.phtml');
			}
			else echo $view->render('home.phtml');
			?>
			
			<div id="content">      
<?php 
echo $this->layout()->content;
?>
			</div>
			<?php if ($this->game) echo $view->render('footer.phtml'); else echo '<div id="push"></div>';?>
			
		</div><?php 	if (!$this->game) echo $view->render('footer.phtml');?> 
<?php 
if ($this->module=="default") {
	echo ' <div id="login" title="Login">';
	$login=new Form_LoginForm();
	//$login->setAction($this->url(array('controller'=>'login')));
	echo $login.'</div>
			<div id="reg" title="[REG]">';
	$reg=new Form_Register();
	$reg->setAction($this->url(array('controller'=>'reg')));
	echo $reg.'</div>';
}
 // account
		if ($this->auth->hasIdentity()) {
			$v=new Zend_View();
			$v->option=array(
					//'prova'=>array(
					//		'name'=>'[PROVA]',
					//		'value'=>'prova',
					//		'label'=>''//if null display value
					//		'type'=>'Input'// default or Select or Textarea
					//		'option'=>array())
			);
			$user=Model_user::getInstance();
			$v->addFilter('Tmpeng')->addFilterPath(APPLICATION_PATH.'/plugin');
			$v->setScriptPath(APPLICATION_PATH.'/views/scripts/account/');
			$key=array('NICK'=>$user->data['username'],'EMAIL'=>$user->data['email']);
			Zend_View_Filter_Tmpeng::addkey($key);
			echo '<div id="account" title="[ACCOUNT]">'.$v->render('index.phtml').'</div>';
		}
		?>
		<div id="credits">
<h3><a href="http://blogpagliaccio.wordpress.com" target="_blanc" >Pagliaccio</a></h3>
<p>
    Ideatore, amministratore e realizzatore del gioco. Programmatore php, javascript.
</p>
<h3><a href="http://leonardosite.altervista.org" target="_blanc" >Leonardo I</a></h3>
<p>
    Co-amministratore e realizzatore del gioco. Programmatore php, javascript.
</p>



<h3>ringraziamo i segunti tool per il supporto dato:</h3>

    <a href="http://validator.w3.org/check?uri=referer">
        <img
        src="http://www.w3.org/Icons/valid-xhtml10"
        alt="Valid XHTML 1.0 Transitional" height="31" width="88" />
    </a>

<a href="http://www.linux.org"><img src="<?php echo $this->baseUrl()?>/common/images/linux_icon.gif" alt="linux" height="60" width="65" /></a>
<a href="http://apache.org/"><img src="<?php echo $this->baseUrl()?>/common/images/apache_icon.gif" alt="apache" height="50" width="72" /></a>
<a href="http://www.mysql.it"><img src="<?php echo $this->baseUrl()?>/common/images/mysql_icon.gif" alt="mysql" height="37" width="63" /></a>
<a href="http://www.php.net"><img src="<?php echo $this->baseUrl()?>/common/images/php_icon.gif" alt="php" height="35" width="44" /></a>
<a href="http://www.zend.com/"><img src="<?php echo $this->baseUrl()?>/common/images/zend.png" alt="zend" height="50" width="50" /></a>

</div>

	</body>
</html>