<?php
//init
header('Content-Type:text/html; charset=UTF-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Age of Evolution');
//init variable
$auth = Zend_Auth::getInstance();
$req = Zend_Controller_Front::getInstance()->getRequest();
$module = $req->getModuleName();
$action = $req->getActionName();
$controller = $req->getControllerName();
$alerts = false;
if ($auth->hasIdentity()) {
    $alerts=Model_alerts::getAlerts();
}
if (! $alerts)
    $alerts[0] = false;
//$menu=new Zend_View_Helper_MyMenu();
//*******************************************init menu
$iconSize=16;
$path=$this->baseUrl();
$this->myMenu()
	->add('Home','default','index','index',1,null,null,$path.'/common/images/home.png',$iconSize,false)
	->add('Forum','forum',null,null,2,null,null,$path.'/common/images/forum.ico',$iconSize,false)
	->add('Wiki','wiki',null,null,3,null,null,$path.'/common/images/wiki-icon.png',$iconSize,false)
	->add('Login','default','login','index',4,'login','index',$path.'/common/images/login.gif',$iconSize,false)
	->add('[REG]','default','reg','index',5,'reg','index',$path.'/common/images/add.png',$iconSize,false)
	->add('Logout','default','login','logout',6,'login','logout',$path.'/common/images/logout.png',$iconSize,false)
	->add('[PROFILE]','default','account','index',7,'account',null,$path.'/common/images/modacc.png',$iconSize,false)
	->add('[BUG]','javascript:ev.bugreport();',null,null,20,'priv_zone',null,$path.'/common/images/bug.png',$iconSize,false)
	->add(array('label'=>'Admin'
			,'module'=>'admin'
			//,'controller'=>'index'
			//,'action'=>'index'
			,'order'=>100
			,'resource'=>'admin'
			,'icon'=>$path.'/common/images/village/corona.gif'
			,'iconSize'=>$iconSize
			,'text'=>false
		)
	)
	->add('Help',"javascript:ev.help('index');",null,null,99,null,null,$path.'/common/images/help.png',$iconSize,false);

if ($module=='admin') {
	$this->myMenu()->add(array('label'=>'[MKDATA]'
					,'module'=>'admin'
					,'controller'=>'mkdata'
					,'order'=>8
					,'resource'=>'admin'
	))->add(array('label'=>'[ALERTS]'
					,'module'=>'admin'
					,'controller'=>'track'
					,'order'=>9
					,'resource'=>'admin'
	))->add(array('label'=>'[MAP]'
					,'module'=>'admin'
					,'controller'=>'generate'
					,'order'=>10
					,'resource'=>'admin'
	))->add(array('label'=>'[MAINTENAINCE]'
					,'module'=>'admin'
					,'controller'=>'maintenance'
					,'order'=>11
					,'resource'=>'admin'
	))->add(array('label'=>'F.a.q'
					,'module'=>'admin'
					,'controller'=>'faq'
					,'order'=>12
					,'resource'=>'admin'
	));
}

//feed 
$ev = $config = Zend_Registry::get('config');
if ($ev->local) $news='<li>le news non funzionano in locale</li>';
else{
	try {
    	$feed =Zend_Feed::import('http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/feed/');
	} catch (Zend_Feed_Exception $e) {
    // feed import failed
   		$feed=array();
	}
	$news="";
// Loop over each channel item and store relevant data
	foreach ($feed as $item) {
		$date=new DateTime($item->pubDate());
		$news.='<li><span>'.$date->format("d/m/Y").'</span> <a href="'.$item->link().'">'.$item->title().'</a></li>';
	}
}

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta name="DESCRIPTION" content="browser game gratuito, gestionale in cui i giocatori comandano civiltà, portandole ad evolversi dalla preistoria fino al futuro" />
		<meta name="KEYWORDS" content="browsergame,strategia,gestionale,evoluzione,gratis" />
		<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/favicon.ico" />	
<?php
		echo $this->headLink()->prependStylesheet(
		$this->baseUrl() . '/common/css/css.php');
		$this->headScript()->captureStart();
		//******************************************logger*******************************************************
		
		if ($this->logger) {
			foreach ($this->logger as $log) {
				echo 'console.log("'.$log['timestamp'].' - '.$log['priorityName'].' - '.($log['info']? $log[info].': ' : '').'",'.$log['message'].');';
			}
		}
		?>
$(document).ready(function(){
    //***************************controllo aggiornamento script
    if (ev.revision<67) {
	    if (confirm('<?php echo $this->t->_('alcuni file (.js /.css) sono stati aggiornati, ma nel suo pc è presente una versione vecchia. la pagina verrà ricaricata per aggiornare la cache.');?>'))
	    	location.reload();
    }
	$("ul#news").liScroll();
	$("[title]:not(.context-menu div)").tooltip({
		   offset: [-10, 0],
		   delay:1,
		   predelay:400
		}).dynamic({ bottom: { direction: 'down'} });
	counter();
	$('input:submit,input:button,button:not(.img)').button();
	$(".password").keyup(function(){
		ev.ctrlpass();
	});
	$(".email").change(function() {
		ev.ctrlemail(this);
	});
	$(".number").keyup(function(){
		ev.ctrlnum(this);
	});
	setTimeout(ev.showalert,3000);
	ev.alertstak=<?php echo json_encode($alerts);?>;
	<?php
	if ($auth->hasIdentity()) {
    	$cat = Zend_Db_Table::getDefaultAdapter()->fetchAll("SELECT * FROM `site_track_cat`");
    foreach ($cat as $value) {
        $cate .= '<option value="' . $value['id'] . '" title="' .
         $value['description'] . '">' . $value['name'] . '</option>';
    }
    $content = array('title' => '[bugreport]', 
    'text' => ('
<div id="report"></div>
<div id="form">
	<div id="type">
		<input type="radio" id="type1" name="type" checked="checked" value="bug" /><label for="type1">' .
     $this->image('/common/images/bug.png', 'bug', null, 32, 32) .
     '</label>
		<input type="radio" id="type2" name="type"  value="idea" /><label for="type2">' .
     $this->image('/common/images/idea.gif', '[idee]', null, 32, 32) .
     '</label>
		<input type="radio" id="type3" name="type" value="notlike" /><label for="type3">' .
     $this->image('/common/images/notlike.gif', '[lamentele]', null, 32, 
    32) . '</label>
	</div>
	<div>
		<select id="category">' . $cate .
     '</select>
	</div>
	<div>tags : <span id="itag"></span> <input id="tag" />
	<button onclick="ev.addtag($(\'#tag\').val());">' .
     '[inserisci/elimina]' .
     '</button></div>
	<textarea cols="42" rows="14" style="border:1px solid black;" id="description">' . 
    '[descrivi qui il bug che hai trovato, un idea per migliorare il gioco o quello che non ti piace.
	cerca di essere chiaro e di compilare bene il form]' .
     '</textarea>
	<div>' .
     
    '[se vuoi inviarci immagini caricale su un host online e metti qui l&apos;indirizzo]' .
     '</div>
	<div><input id="link" /></div>
	<div style="float: right;"><button onclick="ev.sendbug()">' .
     '[invia]' . '</button></div>
</div><script type="text/javascript">$("#type").buttonset();$("button").button();
$(function() {
var cache = {},
lastXhr;
$( "#tag" ).autocomplete({
minLength: 1,
source: function( request, response ) {
var term = request.term;
if ( term in cache ) {
response( cache[ term ] );
return;
}
lastXhr = $.getJSON( path+"/track/auto", request, function( data, status, xhr ) {
cache[ term ] = data;
if ( xhr === lastXhr ) {
response( data );
}
});
}
});
});
	</' . 'script>'));
    echo 'ev.bugcontent=' . json_encode($content) . ';';
}
?>
});
var path='<?php echo $this->baseUrl();?>';
var module='<?php echo $module; ?>';
ev.parsedata({ alertstak:'<?php echo json_encode($alerts);?>'});

<?php
$this->headScript()->captureEnd();
		echo $this->headScript()->prependFile($this->baseUrl('/common/js/js.php'));

echo $this->headTitle();
?>
	</head>
	<body>
		<!-- SELECT LOCALE -->
		<div id="locale">
			language
			<form action="<?php echo $this->url();?>">
			<?php 
			$list=array_merge(array('browser'=>'auto'),$this->t->getList());
			echo $this->formSelect('locale',$_COOKIE['locale'],array('onchange'=>'submit();','id'=>'loc'),$list);
			?>
			</form>
		</div>
		<div id="container">
			<div id="load"></div>
			<div id="top">
				<table>
					<tr>
						<td style="width: 20%;"><?php echo $this->partial('right.phtml');?></td>
						<td style="width: 20%;"> <?php
							echo '<span id="timestamp" style="display:none">' . mktime() .'000</span>' .
 								"[Ora del server]" . ': <br/><span id="timedisp">' . date("d/m/Y H:i:s") .'</span>';?>
 						</td>
						<td style="width: 30%;">
							<div id="navigation">
<?php 							echo $this->myMenu();?>							
							</div>
						</td>
						<td style="width: 30%;"> <?php echo '<ul id="news"><li><span>AGE OF EVOLUTION</span><a href="http://blogpagliaccio.wordpress.com/category/progetti/age-of-evolution/">News</a></li>'.$news.'</ul>';?> </td>
					</tr>
				</table>
			</div>
			<div id="sinistra">
<?php
if (! $ev->local) {
/*/pubblicità adsense
echo '
<script type="text/javascript"><!--
google_ad_client = "ca-pub-2668371131665980";
// banner_dx 
google_ad_slot = "3462675419";
google_ad_width = 120;
google_ad_height = 600;
//-->
</script> <script type="text/javascript"
	src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script>';
// altervista */

echo "<script type=\"text/javascript\">
/* <![CDATA[ */
document.write('<s'+'cript type=\"text/javascript\" src=\"http://ad.altervista.org/js.ad/size=120X600/r='+new Date().getTime()+'\"><\/s'+'cript>');
/* ]]> */
</script>";

}
?>
			</div>
			<div id="content">      
<?php 			echo $this->layout()->content;?>
			</div>
		</div>   
<?php 	echo $this->partial('footer.phtml');?> 
	</body>
</html>